---
- hosts: dev
  become: True
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: Yes
    - name: Start docker container
      docker_container:
        name: ansibledemo
        image: "ayushkumar047/ansibledemo:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
         
